#hostdisplay
scoreboard players set @p playeramount 0
execute @a ~ ~ ~ scoreboard players add @a[tag=mainhost] playeramount 1
execute @s[scores={playeramount=1}] ~ ~ ~ title @s actionbar §e1§f/50
execute @s[scores={playeramount=2}] ~ ~ ~ title @s actionbar §e2§f/50
execute @s[scores={playeramount=3}] ~ ~ ~ title @s actionbar §e3§f/50
execute @s[scores={playeramount=4}] ~ ~ ~ title @s actionbar §e4§f/50
execute @s[scores={playeramount=5}] ~ ~ ~ title @s actionbar §e5§f/50
execute @s[scores={playeramount=6}] ~ ~ ~ title @s actionbar §e6§f/50
execute @s[scores={playeramount=7}] ~ ~ ~ title @s actionbar §e7§f/50
execute @s[scores={playeramount=8}] ~ ~ ~ title @s actionbar §e8§f/50
execute @s[scores={playeramount=9}] ~ ~ ~ title @s actionbar §e9§f/50
execute @s[scores={playeramount=10}] ~ ~ ~ title @s actionbar §e10§f/50
execute @s[scores={playeramount=11}] ~ ~ ~ title @s actionbar §e11§f/50
execute @s[scores={playeramount=12}] ~ ~ ~ title @s actionbar §e12§f/50
execute @s[scores={playeramount=13}] ~ ~ ~ title @s actionbar §e13§f/50
execute @s[scores={playeramount=14}] ~ ~ ~ title @s actionbar §e14§f/50
execute @s[scores={playeramount=15}] ~ ~ ~ title @s actionbar §e15§f/50
execute @s[scores={playeramount=16}] ~ ~ ~ title @s actionbar §e16§f/50
execute @s[scores={playeramount=17}] ~ ~ ~ title @s actionbar §e17§f/50
execute @s[scores={playeramount=18}] ~ ~ ~ title @s actionbar §e18§f/50
execute @s[scores={playeramount=19}] ~ ~ ~ title @s actionbar §e19§f/50
execute @s[scores={playeramount=20}] ~ ~ ~ title @s actionbar §e20§f/50
execute @s[scores={playeramount=21}] ~ ~ ~ title @s actionbar §e21§f/50
execute @s[scores={playeramount=22}] ~ ~ ~ title @s actionbar §e22§f/50
execute @s[scores={playeramount=23}] ~ ~ ~ title @s actionbar §e23§f/50
execute @s[scores={playeramount=24}] ~ ~ ~ title @s actionbar §e24§f/50
execute @s[scores={playeramount=25}] ~ ~ ~ title @s actionbar §e25§f/50
execute @s[scores={playeramount=26}] ~ ~ ~ title @s actionbar §e26§f/50
execute @s[scores={playeramount=27}] ~ ~ ~ title @s actionbar §e27§f/50
execute @s[scores={playeramount=28}] ~ ~ ~ title @s actionbar §e28§f/50
execute @s[scores={playeramount=29}] ~ ~ ~ title @s actionbar §e29§f/50
execute @s[scores={playeramount=30}] ~ ~ ~ title @s actionbar §e30§f/50
execute @s[scores={playeramount=31}] ~ ~ ~ title @s actionbar §e31§f/50
execute @s[scores={playeramount=32}] ~ ~ ~ title @s actionbar §e32§f/50
execute @s[scores={playeramount=33}] ~ ~ ~ title @s actionbar §e33§f/50
execute @s[scores={playeramount=34}] ~ ~ ~ title @s actionbar §e34§f/50
execute @s[scores={playeramount=35}] ~ ~ ~ title @s actionbar §e35§f/50
execute @s[scores={playeramount=36}] ~ ~ ~ title @s actionbar §e36§f/50
execute @s[scores={playeramount=37}] ~ ~ ~ title @s actionbar §e37§f/50
execute @s[scores={playeramount=38}] ~ ~ ~ title @s actionbar §e38§f/50
execute @s[scores={playeramount=39}] ~ ~ ~ title @s actionbar §e39§f/50
execute @s[scores={playeramount=40}] ~ ~ ~ title @s actionbar §e40§f/50
execute @s[scores={playeramount=41}] ~ ~ ~ title @s actionbar §e41§f/50
execute @s[scores={playeramount=42}] ~ ~ ~ title @s actionbar §e42§f/50
execute @s[scores={playeramount=43}] ~ ~ ~ title @s actionbar §e43§f/50
execute @s[scores={playeramount=44}] ~ ~ ~ title @s actionbar §e44§f/50
execute @s[scores={playeramount=45}] ~ ~ ~ title @s actionbar §e45§f/50
execute @s[scores={playeramount=46}] ~ ~ ~ title @s actionbar §e46§f/50
execute @s[scores={playeramount=47}] ~ ~ ~ title @s actionbar §e47§f/50
execute @s[scores={playeramount=48}] ~ ~ ~ title @s actionbar §e48§f/50
execute @s[scores={playeramount=49}] ~ ~ ~ title @s actionbar §e49§f/50
execute @s[scores={playeramount=50}] ~ ~ ~ title @s actionbar §e50§f/50