scoreboard objectives remove setup
scoreboard objectives remove exp_gameplay
scoreboard objectives remove edu_edition
scoreboard objectives remove setup_process
scoreboard objectives remove interrupt
scoreboard objectives remove hostlang
scoreboard objectives remove createprocess
scoreboard objectives remove teststart
scoreboard objectives remove starting
scoreboard objectives remove starting_timer
scoreboard objectives remove teamspaceleft
scoreboard objectives remove createtimer
scoreboard objectives remove addsc
scoreboard objectives remove positions
scoreboard objectives remove createtimer
scoreboard objectives remove ipvp
scoreboard objectives remove stalking
tag @a remove vip
tag @a remove voted
tag @a remove voting
tag @a remove vjoined
tag @a remove gotparticle
tag @a remove positioned
tag @a remove spread
tag @a remove spectate