titleraw @a[scores={team=1}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=1}]"}]}}]} 
titleraw @a[scores={team=2}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=2}]"}]}}]} 
titleraw @a[scores={team=3}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=3}]"}]}}]} 
titleraw @a[scores={team=4}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=4}]"}]}}]} 
titleraw @a[scores={team=5}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=5}]"}]}}]} 
titleraw @a[scores={team=6}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=6}]"}]}}]} 
titleraw @a[scores={team=7}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=7}]"}]}}]} 
titleraw @a[scores={team=8}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=8}]"}]}}]} 
titleraw @a[scores={team=9}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=9}]"}]}}]} 
titleraw @a[scores={team=10}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=10}]"}]}}]} 
titleraw @a[scores={team=11}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=11}]"}]}}]} 
titleraw @a[scores={team=12}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=12}]"}]}}]} 
titleraw @a[scores={team=13}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=13}]"}]}}]} 
titleraw @a[scores={team=14}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=14}]"}]}}]} 
titleraw @a[scores={team=15}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=15}]"}]}}]} 
titleraw @a[scores={team=16}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=16}]"}]}}]} 
titleraw @a[scores={team=17}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=17}]"}]}}]} 
titleraw @a[scores={team=18}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=18}]"}]}}]} 
titleraw @a[scores={team=19}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=19}]"}]}}]} 
titleraw @a[scores={team=20}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=20}]"}]}}]} 
titleraw @a[scores={team=21}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=21}]"}]}}]} 
titleraw @a[scores={team=22}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=22}]"}]}}]} 
titleraw @a[scores={team=23}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=23}]"}]}}]} 
titleraw @a[scores={team=24}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=24}]"}]}}]} 
titleraw @a[scores={team=25}] actionbar {"rawtext":[{"translate":"team.display","with":{"rawtext":[{"selector":"@a[scores={team=25}]"}]}}]} 