replaceitem entity @s slot.inventory 0 keep uhc:slot
replaceitem entity @s slot.inventory 1 keep uhc:slot
replaceitem entity @s slot.inventory 2 keep uhc:slot
replaceitem entity @s slot.inventory 3 keep uhc:slot
replaceitem entity @s slot.inventory 4 keep uhc:slot
replaceitem entity @s slot.inventory 5 keep uhc:slot
replaceitem entity @s slot.inventory 6 keep uhc:slot
replaceitem entity @s slot.inventory 7 keep uhc:slot
replaceitem entity @s slot.inventory 8 keep uhc:slot
replaceitem entity @s slot.inventory 9 keep uhc:slot
replaceitem entity @s slot.inventory 10 keep uhc:slot
replaceitem entity @s slot.inventory 11 keep uhc:slot
replaceitem entity @s slot.inventory 12 keep uhc:slot
replaceitem entity @s slot.inventory 13 keep uhc:slot
replaceitem entity @s slot.inventory 14 keep uhc:slot
replaceitem entity @s slot.inventory 15 keep uhc:slot
replaceitem entity @s slot.inventory 16 keep uhc:slot
replaceitem entity @s slot.inventory 17 keep uhc:slot
replaceitem entity @s slot.inventory 18 keep uhc:slot
replaceitem entity @s slot.inventory 19 keep uhc:slot
replaceitem entity @s slot.inventory 20 keep uhc:slot
replaceitem entity @s slot.inventory 21 keep uhc:slot
replaceitem entity @s slot.inventory 22 keep uhc:slot
replaceitem entity @s slot.inventory 23 keep uhc:slot
replaceitem entity @s slot.inventory 24 keep uhc:slot
replaceitem entity @s slot.inventory 25 keep uhc:slot
replaceitem entity @s slot.inventory 26 keep uhc:slot
replaceitem entity @s slot.hotbar 1 keep uhc:slot
replaceitem entity @s slot.hotbar 2 keep uhc:slot
replaceitem entity @s slot.hotbar 3 keep uhc:slot
replaceitem entity @s slot.hotbar 4 keep uhc:slot
replaceitem entity @s slot.hotbar 5 keep uhc:slot
replaceitem entity @s slot.hotbar 6 keep uhc:slot
replaceitem entity @s[tag=!mainhost] slot.hotbar 7 keep uhc:slot
replaceitem entity @s[tag=!mainhost] slot.hotbar 8 keep uhc:slot